[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "public"
[[plugins]]
  package = "netlify-plugin-search-index"
    [plugins.inputs]
      exclude = ['/ignore-this-file.html']
[[plugins]]
package = "netlify-plugin-cache-nextjs"