export const FETCHING_ALL_POSTS = 'FETCHING_ALL_POSTS';
export const FETCHING_ALL_POSTS_FAILED = 'FETCHING_ALL_POSTS_FAILED';
export const FETCHING_ALL_POSTS_SUCCESS = 'FETCHING_ALL_POSTS_SUCCESS';
export const FETCHING_SINGLE_POST = 'FETCHING_SINGLE_POST';
export const FETCHING_SINGLE_POST_SUCCESS = 'FETCHING_SINGLE_POST_SUCCESS';
export const FETCHING_SINGLE_POST_FAILED = 'FETCHING_SINGLE_POST_FAILED';
